Server=127.0.0.1:10052
ProxyConfigFrequency=10
Hostname=wjy
ListenPort=10051
ListenIP=0.0.0.0
SourceIP=
LogType=console
LogFile=
LogFileSize=1
DebugLevel=3
StartPollers=1
StartPollersUnreachable=1
StartWorkerThreads=1
StartTrappers=1
StartPingers=1
StartDiscoverers=1
StartHTTPPollers=1
StartTimers=1
Timeout=4
CacheSize=8
CacheUpdateFrequency=60
MaxConcurrentChecks=100
